language: node_js
node_js:
    - 0.8
before_install:
    - jdk_switcher use openjdk6
install: ./travis-ci.py
env: PATH=/home/travis/builds/ArchipelProject/Archipel/narwhal/bin:$PATH CAPP_BUILD=/home/travis/builds/ArchipelProject/Archipel/Cappuccino NARWHAL_ENGINE=rhino
