language: node_js
node_js:
    - 0.8
before_install:
    - jdk_switcher use openjdk6
install: ./travis-ci.py
env:
    global:
        - CAPP_SOURCE=`pwd`/ArchipelProject/Archipel/Libraries/Cappuccino/
        - INSTALL_DIR=$CAPP_SOURCE/Install
        - PATH=$INSTALL_DIR/bin/:$PATH
        - CAPP_BUILD=$CAPP_SOURCE/Build"
        - NARWHAL_ENGINE=rhino
